gcc_gdb_server:
  build: .
  dockerfile: ./Docker-compose/gcc_gdb_server/Dockerfile
  
setting_parser:
  build: .
  dockerfile: ./Docker-compose/setting_parser/Dockerfile
  container_name: setting_parser
  privileged: true
  entrypoint: "gdb myapp"

list:
  build: .
  dockerfile: ./Docker-compose/list/Dockerfile
  container_name: list
  privileged: true
  entrypoint: "gdb myapp"

list_memtest:
  build: .
  dockerfile: ./Docker-compose/list/Dockerfile
  container_name: list_memtest
  privileged: true
  entrypoint: "valgrind --leak-check=yes ./myapp"

hash_table:
  build: .
  dockerfile: ./Docker-compose/hash_table/Dockerfile
  container_name: hash_table
  privileged: true
  entrypoint: "gdb myapp"

hash_table_memtest:
  build: .
  dockerfile: ./Docker-compose/hash_table/Dockerfile
  container_name: hash_table_memtest
  privileged: true
  entrypoint: "valgrind --leak-check=yes ./myapp"

connect_server:
  build: .
  dockerfile: ./Docker-compose/connection_test_server/Dockerfile
  container_name: connect_server
  volumes:
    - tmp:/tmp
  privileged: true
  entrypoint: "gdb server" 

connect_client:
  build: .
  dockerfile: ./Docker-compose/connection_test_client/Dockerfile
  container_name: connect_client
  volumes:
    - tmp:/tmp
  privileged: true
  entrypoint: "gdb client"

chatty:
  build: .
  dockerfile: ./Docker-compose/chatty_server/Dockerfile
  container_name: chatty_server
  volumes:
    - tmp:/tmp
  privileged: true
  entrypoint: "gdb --args ./chatty -f Config/chatty.conf1"

chatty_memdebug:
  build: .
  dockerfile: ./Docker-compose/chatty_server/Dockerfile
  container_name: chatty_server_memdebug
  volumes:
    - tmp:/tmp
  privileged: true
  entrypoint: "valgrind --leak-check=yes --leak-check=full --show-leak-kinds=all --track-origins=yes ./chatty -f Config/chatty.conf1"

client:
  build: .
  dockerfile: ./Docker-compose/chatty_client/Dockerfile
  container_name: chatty_client
  volumes:
    - tmp:/tmp
  privileged: true
  entrypoint: "gdb client"

make:
  build: .
  dockerfile: ./Docker-compose/make/Dockerfile
  container_name: make
  volumes:
    - tmp:/tmp
  privileged: true
  entrypoint: "make"

workspace:
  build: .
  dockerfile: ./Docker-compose/make/Dockerfile
  container_name: workspace
  volumes:
    - tmp:/tmp
  privileged: true
  entrypoint: ""
