
# @Author: angelini.mattia
# @StudentCode: 502688

FROM ubuntu:16.04

RUN apt-get update
RUN apt-get install -y gcc
RUN apt-get install -y gdb
RUN apt-get install -y gdbserver
RUN apt-get install -y valgrind
RUN apt-get install -y make
RUN apt-get install -y psmisc
RUN apt-get install less
